### ISSUE TITLE
1.5.9.589-dev crashing only server side java.lang.NoClassDefFoundError: li/cil/oc/common/init/Items$$anon$1

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#1098]
Seems the latest Dev Build is crashing server side only client is fine "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: li/cil/oc/common/init/Items$$anon$1"
Forge 1291, MC 1.7, OC 1.5.9.589-dev
Crashlog: http://tehnut.info/share/EfqqweWif.txt

The following conversation was in #notenoughmods

+Katie: TehNut, he's been off for around 6ish hours.. I'm an op in #oc though, pastbin it and I'll be happy to forward it to him
+TehNut: I'm probably being stupid, but latest build crashes on the server http://tehnut.info/share/EfqqweWif.txt
+Katie: Hmmm.. Almost looks like something is trying to access a non existent API method..
+TehNut: The only mods I know of that do any OC stuff in there are Sanguimancy, Big Reactors, and Computronics...
+Katie: Someone had an issue like this with a Thaumcraft addon the other day.. IDK if it's one of the ones you have though
+TehNut: I know for a fact that Tom hasn't updated the OC lib in Sanguimancy for a very long time...
+TehNut: LOL
+TehNut: The current OC lib for Sanguimancy is OpenComputers-MC1.7.10-1.4.0.6-rc.1-universal.jar
+Katie: Well.. the API hasn't changed a whole lot since then.. that could be it though
+TehNut: I'm just gonna go ahead and update that...
+Katie: I know OpenPrinter still uses OC 1.4's API
+Katie: and it works in 1.5
+TehNut: Either way, still needs an update
+Katie: heh yeah
+TehNut: But unless something major changed since 1.5.3.455...
+TehNut: Also, it works correctly on the client side
+TehNut: It's only server that has issues
+Katie: Yeah.. I don't have a recent OC on a server.. 
+Katie: Hmm.. I wonder if this is NEI being derpy
+TehNut: Same crash in Sanguimancy dev only on server...
+TehNut: Reproducable on Forge 1291 in an environment that doesn't touch OC at all
+TehNut: It's OC and one of my mods and that's it
+Katie: Hm.. kk
+TehNut: too lazy to setup an actual server environment
+TehNut: :D

**Comment by CaitlynMainer** [comment]
Dupe #1097

**Comment by fnuecke** [comment]
Thanks. Stupid assumptions >_>

**Comment by TehNut** [comment]
Heh... :p

**Comment by Tombenpotter** [comment]
See, it wasn't my fault :p
